# Generated by Django 5.2.4 on 2026-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("resumen", models.TextField(blank=True, null=True)),
                ("fuente", models.CharField(max_length=180)),
                ("url_fuente", models.CharField(max_length=500)),
                ("imagen_url", models.CharField(blank=True, max_length=500, null=True)),
                ("fecha_publicacion", models.DateTimeField()),
                ("fecha_sincronizacion", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(max_length=20)),
            ],
        ),
    ]
