# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80, unique=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProyectoAS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=220)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("servicio_propuesto", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(max_length=30)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("resumen_publico", models.TextField(blank=True, null=True)),
                ("es_publico", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Proyecto A+S",
                "verbose_name_plural": "Proyectos A+S",
            },
        ),
        migrations.CreateModel(
            name="EnlaceRegistroEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "creado_por_docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_registro_equipo_creados",
                        to="academico.docente",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_registro_equipo",
                        to="academico.seccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_grupo", models.IntegerField()),
                ("informante_nombre", models.CharField(max_length=180)),
                ("informante_correo", models.CharField(max_length=254)),
                (
                    "informante_entra_id",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(max_length=20)),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipos",
                        to="academico.seccion",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipos",
                        to="proyectos.proyectoas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegranteEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=12)),
                ("nombres", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("correo_institucional", models.CharField(max_length=254)),
                ("es_informante", models.BooleanField(default=False)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrantes",
                        to="proyectos.equipo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegranteEtiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "asignado_por_docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etiquetas_asignadas",
                        to="academico.docente",
                    ),
                ),
                (
                    "etiqueta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integrantes_asignados",
                        to="proyectos.etiqueta",
                    ),
                ),
                (
                    "integrante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etiquetas_asignadas",
                        to="proyectos.integranteequipo",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="integranteequipo",
            constraint=models.UniqueConstraint(
                fields=("equipo", "rut"), name="unique_rut_por_equipo"
            ),
        ),
        migrations.AddConstraint(
            model_name="integranteetiqueta",
            constraint=models.UniqueConstraint(
                fields=("integrante", "etiqueta"), name="unique_etiqueta_por_integrante"
            ),
        ),
        migrations.AddConstraint(
            model_name="equipo",
            constraint=models.UniqueConstraint(
                fields=("seccion", "numero_grupo"),
                name="unique_numero_grupo_por_seccion",
            ),
        ),
    ]
