# Generated by Django 5.2.4 on 2026-09-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='clave_idempotencia',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
