# Generated by Django 5.2.4 on 2026-09-22 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlacePlanificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinatario_tipo', models.CharField(choices=[('DIRECCION', 'Dirección de Carrera'), ('SECRETARIA', 'Secretaría de Estudios')], max_length=20)),
                ('destinatario_nombre', models.CharField(help_text='Nombre del Director o Secretario', max_length=150)),
                ('destinatario_email', models.EmailField(help_text='Correo institucional', max_length=254)),
                ('sede', models.CharField(default='Sede Santiago', max_length=100)),
                ('campus', models.CharField(default='Campus Providencia', max_length=100)),
                ('carrera', models.CharField(default='Ingeniería Civil Informática', max_length=150)),
                ('periodo', models.CharField(default='2026-2', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(help_text='Fecha límite de vigencia')),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces_planificacion_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enlace de Planificación',
                'verbose_name_plural': 'Enlaces de Planificación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
