# Generated by Django 5.2.4 on 2026-09-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_enlaceplanificacion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Seccion",
        ),
    ]
