# Generated by Django 5.2.4 on 2026-09-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0003_delete_seccion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EnlacePlanificacion",
        ),
    ]
