# Generated by Django 5.2.4 on 2026-10-01 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
        ('proyectos', '0003_equipo_socio_comunitario'),
        ('socios', '0003_historialestadosocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSocioEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('cambiado_por_docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_socio_equipos', to='academico.docente')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_socios', to='proyectos.equipo')),
                ('socio_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_equipos_como_anterior', to='socios.sociocomunitario')),
                ('socio_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_equipos_como_nuevo', to='socios.sociocomunitario')),
            ],
        ),
    ]
