# Generated by Django 5.2.4 on 2026-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CargaError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(blank=True, max_length=120, null=True)),
                ("codigo", models.CharField(blank=True, max_length=40, null=True)),
                ("mensaje", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CargaFila",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_fila", models.IntegerField()),
                ("datos_raw_json", models.JSONField()),
                ("estado", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CargaHistorica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_origen", models.CharField(max_length=60)),
                ("hoja", models.CharField(blank=True, max_length=120, null=True)),
                ("fecha_carga", models.DateTimeField()),
                ("estado", models.CharField(max_length=20)),
                ("total_filas", models.IntegerField()),
                ("aceptadas", models.IntegerField()),
                ("observadas", models.IntegerField()),
                ("omitidas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CargaMapeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("columna_origen", models.CharField(max_length=180)),
                ("campo_destino", models.CharField(max_length=180)),
            ],
        ),
    ]
