# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("archivos", "0001_initial"),
        ("encuestas", "0002_initial"),
        ("historicos", "0001_initial"),
        ("socios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargafila",
            name="participacion_resultante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filas_historicas",
                to="socios.participacionsocio",
            ),
        ),
        migrations.AddField(
            model_name="cargafila",
            name="respuesta_resultante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filas_historicas",
                to="encuestas.respuestaformulario",
            ),
        ),
        migrations.AddField(
            model_name="cargafila",
            name="socio_resultante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filas_historicas",
                to="socios.sociocomunitario",
            ),
        ),
        migrations.AddField(
            model_name="cargaerror",
            name="fila",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="errores",
                to="historicos.cargafila",
            ),
        ),
        migrations.AddField(
            model_name="cargahistorica",
            name="archivo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carga_historica",
                to="archivos.archivo",
            ),
        ),
    ]
