# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("historicos", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cargahistorica",
            name="responsable_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargas_historicas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cargafila",
            name="carga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filas",
                to="historicos.cargahistorica",
            ),
        ),
        migrations.AddField(
            model_name="cargamapeo",
            name="carga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mapeos",
                to="historicos.cargahistorica",
            ),
        ),
        migrations.AddConstraint(
            model_name="cargafila",
            constraint=models.UniqueConstraint(
                fields=("carga", "numero_fila"), name="unique_numero_fila_por_carga"
            ),
        ),
    ]
