# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("archivos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartaEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("rut", models.CharField(max_length=12)),
                ("orden", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SolicitudCarta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solicitante_tipo", models.CharField(max_length=20)),
                ("solicitante_nombre", models.CharField(max_length=180)),
                ("solicitante_correo", models.CharField(max_length=254)),
                (
                    "solicitante_entra_id",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("institucion_receptora", models.CharField(max_length=220)),
                ("persona_receptora", models.CharField(max_length=180)),
                (
                    "cargo_receptor",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("consideraciones", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(max_length=30)),
                ("motivo_observacion", models.TextField(blank=True, null=True)),
                ("fecha_solicitud", models.DateTimeField()),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CartaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_version", models.IntegerField()),
                ("tipo", models.CharField(max_length=20)),
                ("fecha_generacion", models.DateTimeField()),
                (
                    "hash_documento",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "archivo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documento_carta",
                        to="archivos.archivo",
                    ),
                ),
            ],
        ),
    ]
