# Generated by Django 5.2.4 on 2026-09-25 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        ("archivos", "0001_initial"),
        ("proyectos", "0005_initial"),
        ("socios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudCarta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solicitante_nombre", models.CharField(max_length=180)),
                ("solicitante_tipo", models.CharField(max_length=20)),
                ("solicitante_correo", models.CharField(max_length=160)),
                ("solicitante_rut", models.CharField(max_length=254)),
                (
                    "solicitante_entra_id",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("institucion_receptora", models.CharField(max_length=220)),
                ("persona_receptora", models.CharField(max_length=180)),
                (
                    "cargo_receptor",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("consideraciones", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(max_length=30)),
                ("motivo_observacion", models.TextField(blank=True, null=True)),
                ("fecha_solicitud", models.DateTimeField()),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_carta",
                        to="academico.campus",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_carta",
                        to="proyectos.equipo",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_carta",
                        to="academico.seccion",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_carta",
                        to="academico.sede",
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_carta",
                        to="socios.sociocomunitario",
                    ),
                ),
                (
                    "solicitante_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_carta",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartaEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("rut", models.CharField(max_length=12)),
                ("orden", models.SmallIntegerField()),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudiantes",
                        to="cartas.solicitudcarta",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("solicitud", "orden"),
                        name="unique_orden_estudiante_por_solicitud",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CartaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_version", models.IntegerField()),
                ("tipo", models.CharField(max_length=20)),
                ("fecha_generacion", models.DateTimeField()),
                (
                    "hash_documento",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "archivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos_carta",
                        to="archivos.archivo",
                    ),
                ),
                (
                    "generado_por_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos_carta_generados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="cartas.solicitudcarta",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("solicitud", "numero_version"),
                        name="unique_version_documento_por_solicitud",
                    )
                ],
            },
        ),
    ]
