# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0002_initial"),
        ("cartas", "0001_initial"),
        ("proyectos", "0001_initial"),
        ("socios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cartadocumento",
            name="generado_por_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos_carta_generados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitudcarta",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solicitudes_carta",
                to="academico.campus",
            ),
        ),
        migrations.AddField(
            model_name="solicitudcarta",
            name="docente_derivador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solicitudes_carta_derivadas",
                to="academico.docente",
            ),
        ),
        migrations.AddField(
            model_name="solicitudcarta",
            name="equipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_carta",
                to="proyectos.equipo",
            ),
        ),
        migrations.AddField(
            model_name="solicitudcarta",
            name="seccion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solicitudes_carta",
                to="academico.seccion",
            ),
        ),
        migrations.AddField(
            model_name="solicitudcarta",
            name="sede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solicitudes_carta",
                to="academico.sede",
            ),
        ),
        migrations.AddField(
            model_name="solicitudcarta",
            name="socio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_carta",
                to="socios.sociocomunitario",
            ),
        ),
        migrations.AddField(
            model_name="solicitudcarta",
            name="solicitante_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_carta",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cartaestudiante",
            name="solicitud",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estudiantes",
                to="cartas.solicitudcarta",
            ),
        ),
        migrations.AddField(
            model_name="cartadocumento",
            name="solicitud",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="cartas.solicitudcarta",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartaestudiante",
            constraint=models.UniqueConstraint(
                fields=("solicitud", "orden"),
                name="unique_orden_estudiante_por_solicitud",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartadocumento",
            constraint=models.UniqueConstraint(
                fields=("solicitud", "numero_version"),
                name="unique_version_documento_por_solicitud",
            ),
        ),
    ]
