# Generated by Django 5.2.4 on 2026-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditoriaCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_externo",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("entidad", models.CharField(max_length=120)),
                ("entidad_id", models.CharField(max_length=80)),
                ("accion", models.CharField(max_length=60)),
                ("valores_anteriores_json", models.JSONField(blank=True, null=True)),
                ("valores_nuevos_json", models.JSONField(blank=True, null=True)),
                ("fecha", models.DateTimeField()),
                ("ip", models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
