# Generated by Django 5.2.4 on 2026-09-16 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaPlanificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=20)),
                ('enlace_origen', models.URLField(max_length=500)),
                ('filas_recibidas', models.IntegerField(default=0)),
                ('filas_aceptadas', models.IntegerField(default=0)),
                ('filas_observadas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFilaObservada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.IntegerField()),
                ('nrc', models.CharField(blank=True, max_length=20, null=True)),
                ('causa_error', models.TextField()),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='core.cargaplanificacion')),
            ],
        ),
    ]
