# Generated by Django 5.2.4 on 2026-09-15 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='core.facultad'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='anio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='core.anio'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campus'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodoacademico'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sede'),
        ),
        migrations.AddField(
            model_name='campus',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus', to='core.sede'),
        ),
    ]
