# Generated by Django 5.2.4 on 2026-09-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargaplanificacion',
            name='enlace_origen',
        ),
        migrations.RemoveField(
            model_name='cargaplanificacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cargaplanificacion',
            name='filas_aceptadas',
        ),
        migrations.RemoveField(
            model_name='cargaplanificacion',
            name='filas_observadas',
        ),
        migrations.RemoveField(
            model_name='cargaplanificacion',
            name='filas_recibidas',
        ),
        migrations.RemoveField(
            model_name='cargaplanificacion',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='cargaplanificacion',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='detallefilaobservada',
            name='carga',
        ),
        migrations.RemoveField(
            model_name='detallefilaobservada',
            name='causa_error',
        ),
        migrations.RemoveField(
            model_name='detallefilaobservada',
            name='nrc',
        ),
        migrations.RemoveField(
            model_name='detallefilaobservada',
            name='numero_fila',
        ),
    ]
