# Generated by Django 5.2.4 on 2026-09-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodoacademico",
            name="anio",
        ),
        migrations.RemoveField(
            model_name="asignatura",
            name="carrera",
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="asignatura",
        ),
        migrations.RemoveField(
            model_name="campus",
            name="sede",
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="campus",
        ),
        migrations.RemoveField(
            model_name="carrera",
            name="facultad",
        ),
        migrations.RemoveField(
            model_name="docente",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="docente",
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="periodo",
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="sede",
        ),
        migrations.DeleteModel(
            name="Anio",
        ),
        migrations.DeleteModel(
            name="Asignatura",
        ),
        migrations.DeleteModel(
            name="Campus",
        ),
        migrations.DeleteModel(
            name="Carrera",
        ),
        migrations.DeleteModel(
            name="Facultad",
        ),
        migrations.DeleteModel(
            name="Docente",
        ),
        migrations.DeleteModel(
            name="PeriodoAcademico",
        ),
        migrations.DeleteModel(
            name="Seccion",
        ),
        migrations.DeleteModel(
            name="Sede",
        ),
    ]
