# Generated by Django 5.2.4 on 2026-09-30 02:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cargaplanificacion_enlace_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaplanificacion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cargaplanificacion',
            name='filas_aceptadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargaplanificacion',
            name='filas_observadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargaplanificacion',
            name='filas_recibidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargaplanificacion',
            name='periodo',
            field=models.CharField(default='2026-10', max_length=50),
        ),
        migrations.AddField(
            model_name='cargaplanificacion',
            name='unidad',
            field=models.CharField(default='Departamento de Informática', max_length=255),
        ),
        migrations.AddField(
            model_name='detallefilaobservada',
            name='carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.cargaplanificacion'),
        ),
        migrations.AddField(
            model_name='detallefilaobservada',
            name='causa_error',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='detallefilaobservada',
            name='nrc',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='detallefilaobservada',
            name='numero_fila',
            field=models.IntegerField(default=0),
        ),
    ]
