# Generated by Django 5.2.4 on 2026-09-23 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('ciudad', models.CharField(blank=True, max_length=120, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatura_carreras', to='academico.asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatura_carreras', to='academico.carrera')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='carreras',
            field=models.ManyToManyField(related_name='asignaturas', through='academico.AsignaturaCarrera', to='academico.carrera'),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='academico.facultad'),
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.SmallIntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('anio', 'tipo', 'nombre'), name='unique_periodo_academico')],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.CharField(max_length=20)),
                ('seccion', models.CharField(max_length=20)),
                ('jornada', models.CharField(blank=True, max_length=40, null=True)),
                ('horario', models.CharField(blank=True, max_length=160, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_consolidacion', models.DateTimeField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='academico.asignatura')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='academico.campus')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='academico.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(blank=True, max_length=30, null=True)),
                ('declaracion_as', models.BooleanField(blank=True, null=True)),
                ('estudiantes_planificados', models.IntegerField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion_carreras', to='academico.carrera')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion_carreras', to='academico.seccion')),
            ],
        ),
        migrations.AddField(
            model_name='seccion',
            name='carreras',
            field=models.ManyToManyField(related_name='secciones', through='academico.SeccionCarrera', to='academico.carrera'),
        ),
        migrations.CreateModel(
            name='SeccionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(blank=True, max_length=80, null=True)),
                ('capacitado_as', models.BooleanField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion_docentes', to='academico.docente')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion_docentes', to='academico.seccion')),
            ],
        ),
        migrations.AddField(
            model_name='seccion',
            name='docentes',
            field=models.ManyToManyField(related_name='secciones', through='academico.SeccionDocente', to='academico.docente'),
        ),
        migrations.AddField(
            model_name='campus',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus', to='academico.sede'),
        ),
        migrations.AddConstraint(
            model_name='asignaturacarrera',
            constraint=models.UniqueConstraint(fields=('asignatura', 'carrera'), name='unique_asignatura_carrera'),
        ),
        migrations.AddConstraint(
            model_name='seccioncarrera',
            constraint=models.UniqueConstraint(fields=('seccion', 'carrera'), name='unique_seccion_carrera'),
        ),
        migrations.AddConstraint(
            model_name='secciondocente',
            constraint=models.UniqueConstraint(fields=('seccion', 'docente'), name='unique_seccion_docente'),
        ),
        migrations.AddConstraint(
            model_name='seccion',
            constraint=models.UniqueConstraint(fields=('periodo', 'nrc'), name='unique_periodo_nrc'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('sede', 'nombre'), name='unique_campus_sede_nombre'),
        ),
    ]
