# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("nombres", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("correo_institucional", models.CharField(max_length=254, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Facultad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=60, null=True, unique=True),
                ),
                ("nombre", models.CharField(max_length=160)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PeriodoAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.SmallIntegerField()),
                ("tipo", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=80)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("estado", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nrc", models.CharField(max_length=20)),
                ("seccion", models.CharField(max_length=20)),
                ("jornada", models.CharField(blank=True, max_length=40, null=True)),
                ("horario", models.CharField(blank=True, max_length=160, null=True)),
                ("estado", models.CharField(max_length=20)),
                ("fecha_consolidacion", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SeccionCarrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.CharField(blank=True, max_length=30, null=True)),
                ("declaracion_as", models.BooleanField(blank=True, null=True)),
                (
                    "estudiantes_planificados",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeccionDocente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_contrato",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("capacitado_as", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("ciudad", models.CharField(blank=True, max_length=120, null=True)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="UnidadAcademica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=180)),
                (
                    "correo_oficial",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="AsignaturaCarrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignatura_carreras",
                        to="academico.asignatura",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignatura_carreras",
                        to="academico.carrera",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asignatura",
            name="carreras",
            field=models.ManyToManyField(
                related_name="asignaturas",
                through="academico.AsignaturaCarrera",
                to="academico.carrera",
            ),
        ),
    ]
