# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="docente",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfil_docente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="facultad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carreras",
                to="academico.facultad",
            ),
        ),
        migrations.AddConstraint(
            model_name="periodoacademico",
            constraint=models.UniqueConstraint(
                fields=("anio", "tipo", "nombre"), name="unique_periodo_academico"
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="asignatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secciones",
                to="academico.asignatura",
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secciones",
                to="academico.campus",
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secciones",
                to="academico.periodoacademico",
            ),
        ),
        migrations.AddField(
            model_name="seccioncarrera",
            name="carrera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seccion_carreras",
                to="academico.carrera",
            ),
        ),
        migrations.AddField(
            model_name="seccioncarrera",
            name="seccion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seccion_carreras",
                to="academico.seccion",
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="carreras",
            field=models.ManyToManyField(
                related_name="secciones",
                through="academico.SeccionCarrera",
                to="academico.carrera",
            ),
        ),
        migrations.AddField(
            model_name="secciondocente",
            name="docente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seccion_docentes",
                to="academico.docente",
            ),
        ),
        migrations.AddField(
            model_name="secciondocente",
            name="seccion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seccion_docentes",
                to="academico.seccion",
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="docentes",
            field=models.ManyToManyField(
                related_name="secciones",
                through="academico.SeccionDocente",
                to="academico.docente",
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="sede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campus",
                to="academico.sede",
            ),
        ),
        migrations.AddField(
            model_name="unidadacademica",
            name="carrera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unidades_academicas",
                to="academico.carrera",
            ),
        ),
        migrations.AddField(
            model_name="unidadacademica",
            name="facultad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unidades_academicas",
                to="academico.facultad",
            ),
        ),
        migrations.AddConstraint(
            model_name="asignaturacarrera",
            constraint=models.UniqueConstraint(
                fields=("asignatura", "carrera"), name="unique_asignatura_carrera"
            ),
        ),
        migrations.AddConstraint(
            model_name="seccioncarrera",
            constraint=models.UniqueConstraint(
                fields=("seccion", "carrera"), name="unique_seccion_carrera"
            ),
        ),
        migrations.AddConstraint(
            model_name="secciondocente",
            constraint=models.UniqueConstraint(
                fields=("seccion", "docente"), name="unique_seccion_docente"
            ),
        ),
        migrations.AddConstraint(
            model_name="seccion",
            constraint=models.UniqueConstraint(
                fields=("periodo", "nrc"), name="unique_periodo_nrc"
            ),
        ),
        migrations.AddConstraint(
            model_name="campus",
            constraint=models.UniqueConstraint(
                fields=("sede", "nombre"), name="unique_campus_sede_nombre"
            ),
        ),
    ]
