# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        ("encuestas", "0001_initial"),
        ("proyectos", "0001_initial"),
        ("rutas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClasificacionSocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ContactoSocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("cargo", models.CharField(blank=True, max_length=120, null=True)),
                ("correo", models.CharField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("es_principal", models.BooleanField()),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="SocioComunitario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ("nombre_organizacion", models.CharField(max_length=220)),
                (
                    "clasificacion_otra",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "direccion_exacta",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "centro_servicio",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                ("estado_revision", models.CharField(max_length=30)),
                ("es_provisional", models.BooleanField()),
                ("activo", models.BooleanField()),
                ("fecha_creacion", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Comuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("region", models.CharField(max_length=120)),
                (
                    "lat_centro",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lon_centro",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("activo", models.BooleanField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nombre", "region"), name="unique_comuna_por_region"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Convocatoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=220)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(max_length=20)),
                (
                    "formulario_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="convocatorias",
                        to="encuestas.formularioversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvitacionCierre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("modo_contacto", models.CharField(max_length=20)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("respuesta", models.CharField(max_length=20)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "seccion_ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitaciones_cierre",
                        to="rutas.seccionruta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipacionSocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servicio_realizado", models.TextField(blank=True, null=True)),
                ("beneficiarios_estimados", models.IntegerField(blank=True, null=True)),
                ("evaluacion", models.SmallIntegerField(blank=True, null=True)),
                ("comentario", models.TextField(blank=True, null=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("origen", models.CharField(max_length=30)),
                (
                    "asignatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participaciones_socios",
                        to="academico.asignatura",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participaciones_socios",
                        to="academico.campus",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participaciones_socios",
                        to="academico.carrera",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participaciones_socios",
                        to="proyectos.equipo",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participaciones_socios",
                        to="academico.periodoacademico",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participaciones_socios",
                        to="proyectos.proyectoas",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participaciones_socios",
                        to="academico.seccion",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participaciones_socios",
                        to="academico.sede",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostulacionSocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=30)),
                ("motivo_rechazo", models.TextField(blank=True, null=True)),
                ("fecha_recepcion", models.DateTimeField()),
                ("fecha_revision", models.DateTimeField(blank=True, null=True)),
                (
                    "convocatoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postulaciones",
                        to="socios.convocatoria",
                    ),
                ),
                (
                    "respuesta_formulario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postulacion_socio",
                        to="encuestas.respuestaformulario",
                    ),
                ),
            ],
        ),
    ]
