# Generated by Django 5.2.4 on 2026-09-25 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        ("proyectos", "0005_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClasificacionSocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactoSocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("cargo", models.CharField(blank=True, max_length=120, null=True)),
                ("correo", models.CharField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("es_principal", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("region", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nombre", "region"), name="unique_comuna_por_region"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Convocatoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=220)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("estado", models.CharField(max_length=20)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="convocatorias",
                        to="academico.periodoacademico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipacionSocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("estado", models.CharField(max_length=20)),
                (
                    "contacto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participaciones",
                        to="socios.contactosocio",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participaciones_socios",
                        to="proyectos.proyectoas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvitacionCierre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(editable=False, unique=True)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(max_length=20)),
                (
                    "participacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitaciones_cierre",
                        to="socios.participacionsocio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocioComunitario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=220)),
                ("rut", models.CharField(blank=True, max_length=12, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("correo", models.CharField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "clasificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="socios",
                        to="socios.clasificacionsocio",
                    ),
                ),
                (
                    "comuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="socios",
                        to="socios.comuna",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="participacionsocio",
            name="socio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participaciones",
                to="socios.sociocomunitario",
            ),
        ),
        migrations.AddField(
            model_name="contactosocio",
            name="socio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contactos",
                to="socios.sociocomunitario",
            ),
        ),
        migrations.CreateModel(
            name="PostulacionSocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_postulacion", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(max_length=20)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "contacto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="postulaciones",
                        to="socios.contactosocio",
                    ),
                ),
                (
                    "convocatoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postulaciones",
                        to="socios.convocatoria",
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postulaciones",
                        to="socios.sociocomunitario",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("convocatoria", "socio"),
                        name="unique_socio_por_convocatoria",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="participacionsocio",
            constraint=models.UniqueConstraint(
                fields=("socio", "proyecto"), name="unique_socio_por_proyecto"
            ),
        ),
    ]
