# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("socios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="postulacionsocio",
            name="revisado_por_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="postulaciones_socios_revisadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sociocomunitario",
            name="clasificacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="socios",
                to="socios.clasificacionsocio",
            ),
        ),
        migrations.AddField(
            model_name="sociocomunitario",
            name="comuna",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="socios",
                to="socios.comuna",
            ),
        ),
        migrations.AddField(
            model_name="postulacionsocio",
            name="socio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="postulaciones",
                to="socios.sociocomunitario",
            ),
        ),
        migrations.AddField(
            model_name="participacionsocio",
            name="socio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participaciones",
                to="socios.sociocomunitario",
            ),
        ),
        migrations.AddField(
            model_name="invitacioncierre",
            name="socio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitaciones_cierre",
                to="socios.sociocomunitario",
            ),
        ),
        migrations.AddField(
            model_name="contactosocio",
            name="socio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contactos",
                to="socios.sociocomunitario",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitacioncierre",
            constraint=models.UniqueConstraint(
                fields=("seccion_ruta", "socio"),
                name="unique_invitacion_cierre_seccion_socio",
            ),
        ),
    ]
