# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cartas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaCorreo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=80, unique=True)),
                ("asunto_template", models.CharField(max_length=255)),
                ("cuerpo_template", models.TextField()),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="EnvioCorreo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remitente", models.CharField(max_length=254)),
                ("destinatario", models.CharField(max_length=254)),
                ("asunto", models.CharField(max_length=255)),
                ("cuerpo", models.TextField()),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("OK", "OK"),
                            ("ERROR", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detalle_error", models.TextField(blank=True, null=True)),
                ("numero_intento", models.IntegerField()),
                (
                    "carta_documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envios_correo",
                        to="cartas.cartadocumento",
                    ),
                ),
            ],
        ),
    ]
