# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunicaciones", "0001_initial"),
        ("socios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enviocorreo",
            name="invitacion_cierre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="envios_correo",
                to="socios.invitacioncierre",
            ),
        ),
        migrations.AddField(
            model_name="enviocorreo",
            name="postulacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="envios_correo",
                to="socios.postulacionsocio",
            ),
        ),
        migrations.AddField(
            model_name="enviocorreo",
            name="plantilla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="envios",
                to="comunicaciones.plantillacorreo",
            ),
        ),
    ]
