# Generated by Django 5.2.4 on 2026-09-23 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ('academico', '0001_initial'),
]

    operations = [
        migrations.CreateModel(
            name='PlanificacionAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_acceso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado_registro', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINAL', 'Versión Final')], default='BORRADOR', max_length=15)),
                ('declaracion_as', models.BooleanField(default=False, verbose_name='Declaración A+S')),
                ('nrc', models.CharField(max_length=50, verbose_name='NRC')),
                ('seccion', models.CharField(max_length=20, verbose_name='Sección')),
                ('nivel', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=100)),
                ('estudiantes_planificados', models.IntegerField(verbose_name='Estudiantes Planificados')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.campus')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones_as', to='academico.carrera')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docente')),
            ],
        ),
    ]
