# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=20)),
                ("fecha_guardado", models.DateTimeField(blank=True, null=True)),
                ("fecha_envio_final", models.DateTimeField(blank=True, null=True)),
                ("filas_recibidas", models.IntegerField()),
                ("filas_aceptadas", models.IntegerField()),
                ("filas_observadas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FilaPlanificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_fila", models.IntegerField()),
                (
                    "facultad_texto",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                (
                    "carrera_texto",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                ("declaracion_as", models.BooleanField(blank=True, null=True)),
                ("nrc", models.CharField(max_length=20)),
                (
                    "campus_texto",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("seccion", models.CharField(max_length=20)),
                ("asignatura_texto", models.CharField(max_length=180)),
                ("nivel", models.CharField(blank=True, max_length=30, null=True)),
                ("jornada", models.CharField(blank=True, max_length=40, null=True)),
                ("horario", models.CharField(blank=True, max_length=160, null=True)),
                (
                    "estudiantes_planificados",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "posible_socio_texto",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("estado_validacion", models.CharField(max_length=20)),
                (
                    "asignatura_resuelta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filas_planificacion_resueltas",
                        to="academico.asignatura",
                    ),
                ),
                (
                    "campus_resuelto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filas_planificacion_resueltas",
                        to="academico.campus",
                    ),
                ),
                (
                    "carrera_resuelta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filas_planificacion_resueltas",
                        to="academico.carrera",
                    ),
                ),
                (
                    "seccion_resultante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filas_planificacion_resultantes",
                        to="academico.seccion",
                    ),
                ),
                (
                    "planificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filas",
                        to="planificacion.planificacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilaPlanificacionDocente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(blank=True, max_length=12, null=True)),
                ("nombre", models.CharField(blank=True, max_length=180, null=True)),
                (
                    "tipo_contrato",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("capacitado_as", models.BooleanField(blank=True, null=True)),
                ("correo", models.CharField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "docente_resuelto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filas_planificacion_resueltas",
                        to="academico.docente",
                    ),
                ),
                (
                    "fila",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docentes",
                        to="planificacion.filaplanificacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanificacionEnlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("destinatario_nombre", models.CharField(max_length=180)),
                ("destinatario_correo", models.CharField(max_length=254)),
                ("fecha_emision", models.DateTimeField()),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField()),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_planificacion",
                        to="academico.campus",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_planificacion",
                        to="academico.periodoacademico",
                    ),
                ),
                (
                    "unidad_academica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_planificacion",
                        to="academico.unidadacademica",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="planificacion",
            name="enlace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planificacion",
                to="planificacion.planificacionenlace",
            ),
        ),
        migrations.CreateModel(
            name="PlanificacionError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(blank=True, max_length=80, null=True)),
                ("codigo", models.CharField(blank=True, max_length=40, null=True)),
                ("mensaje", models.TextField()),
                (
                    "fila",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errores",
                        to="planificacion.filaplanificacion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="filaplanificacion",
            constraint=models.UniqueConstraint(
                fields=("planificacion", "numero_fila"),
                name="unique_numero_fila_por_planificacion",
            ),
        ),
    ]
