# Generated by Django 5.2.4 on 2026-09-23 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacionas',
            options={'verbose_name': 'Planificación A+S', 'verbose_name_plural': 'Planificaciones A+S'},
        ),
        migrations.AlterField(
            model_name='planificacionas',
            name='token_acceso',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
