# Generated by Django 5.2.4 on 2026-09-24 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0001_initial"),
        ("planificacion", "0002_alter_planificacionas_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destinatario_correo", models.EmailField(max_length=254)),
                (
                    "token_enlace",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("vence_en", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("BORRADOR", "Borrador"), ("FINAL", "Versión Final")],
                        default="BORRADOR",
                        max_length=15,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planificaciones",
                        to="academico.campus",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planificaciones",
                        to="academico.periodoacademico",
                    ),
                ),
                (
                    "unidad_carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planificaciones",
                        to="academico.carrera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planificación",
                "verbose_name_plural": "Planificaciones",
            },
        ),
        migrations.CreateModel(
            name="FilaPlanificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "declara_as",
                    models.BooleanField(default=False, verbose_name="Declaración A+S"),
                ),
                ("nrc", models.CharField(max_length=50)),
                (
                    "codigo_seccion",
                    models.CharField(max_length=20, verbose_name="Sección"),
                ),
                ("asignatura", models.CharField(max_length=255)),
                ("nivel", models.CharField(max_length=50)),
                ("horario", models.CharField(max_length=255)),
                ("estudiantes", models.PositiveIntegerField()),
                ("datos_docente", models.TextField(blank=True)),
                (
                    "estado_validacion",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("VALIDA", "Válida"),
                            ("OBSERVADA", "Observada"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("errores", models.TextField(blank=True)),
                (
                    "seccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filas_planificacion",
                        to="academico.seccion",
                    ),
                ),
                (
                    "planificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filas",
                        to="planificacion.planificacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fila de planificación",
                "verbose_name_plural": "Filas de planificación",
            },
        ),
        migrations.CreateModel(
            name="PlanificacionError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(blank=True, max_length=100)),
                ("codigo", models.CharField(blank=True, max_length=50)),
                ("mensaje", models.TextField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "fila",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errores_validacion",
                        to="planificacion.filaplanificacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Error de planificación",
                "verbose_name_plural": "Errores de planificación",
            },
        ),
        migrations.CreateModel(
            name="FilaPlanificacionDocente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_principal", models.BooleanField(default=False)),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filas_planificacion",
                        to="academico.docente",
                    ),
                ),
                (
                    "fila",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docentes",
                        to="planificacion.filaplanificacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Docente de fila de planificación",
                "verbose_name_plural": "Docentes de filas de planificación",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fila", "docente"),
                        name="unique_docente_por_fila_planificacion",
                    )
                ],
            },
        ),
    ]
