# Generated by Django 5.2.4 on 2026-09-24 22:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0001_initial"),
        (
            "planificacion",
            "0003_planificacion_filaplanificacion_planificacionerror_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanificacionEnlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "destinatario_tipo",
                    models.CharField(
                        choices=[
                            ("DIRECCION_CARRERA", "Dirección de Carrera"),
                            ("SECRETARIA_ESTUDIOS", "Secretaría de Estudios"),
                        ],
                        max_length=30,
                    ),
                ),
                ("destinatario_nombre", models.CharField(max_length=255)),
                ("destinatario_correo", models.EmailField(max_length=254)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateTimeField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_planificacion",
                        to="academico.campus",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_planificacion",
                        to="academico.carrera",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces_planificacion",
                        to="academico.periodoacademico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enlace de planificación",
                "verbose_name_plural": "Enlaces de planificación",
            },
        ),
        migrations.AddField(
            model_name="planificacion",
            name="enlace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planificaciones",
                to="planificacion.planificacionenlace",
            ),
        ),
    ]
