# Generated by Django 5.2.4 on 2026-09-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
