# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        ("archivos", "0001_initial"),
        ("encuestas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RutaPlantilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="RutaVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_version", models.IntegerField()),
                ("estado", models.CharField(max_length=20)),
                ("fecha_vigencia_desde", models.DateField(blank=True, null=True)),
                ("fecha_vigencia_hasta", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SeccionActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=20)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SeccionRuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=20)),
                (
                    "porcentaje_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExpedienteSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=20)),
                ("fecha_creacion", models.DateTimeField()),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "seccion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expediente",
                        to="academico.seccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "archivo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidencia",
                        to="archivos.archivo",
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="rutas.expedienteseccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RutaActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.CharField(max_length=80)),
                ("nombre", models.CharField(max_length=220)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("es_obligatoria", models.BooleanField()),
                ("orden", models.IntegerField()),
                (
                    "recurso_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("config_recordatorio_json", models.JSONField(blank=True, null=True)),
                (
                    "archivo_recurso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_ruta",
                        to="archivos.archivo",
                    ),
                ),
                (
                    "formulario_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_ruta",
                        to="encuestas.formularioversion",
                    ),
                ),
            ],
        ),
    ]
