# Generated by Django 5.2.4 on 2026-09-25 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        ("archivos", "0001_initial"),
        ("encuestas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RutaPlantilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExpedienteSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=20)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "creado_por_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expedientes_seccion_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seccion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expediente",
                        to="academico.seccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RutaVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_version", models.IntegerField()),
                ("estado", models.CharField(max_length=20)),
                ("fecha_vigencia_desde", models.DateField(blank=True, null=True)),
                ("fecha_vigencia_hasta", models.DateField(blank=True, null=True)),
                (
                    "creado_por_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versiones_ruta_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versiones",
                        to="rutas.rutaplantilla",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RutaActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.CharField(max_length=80)),
                ("nombre", models.CharField(max_length=220)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("es_obligatoria", models.BooleanField()),
                ("orden", models.IntegerField()),
                (
                    "recurso_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("config_recordatorio_json", models.JSONField(blank=True, null=True)),
                (
                    "archivo_recurso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_ruta",
                        to="archivos.archivo",
                    ),
                ),
                (
                    "formulario_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_ruta",
                        to="encuestas.formularioversion",
                    ),
                ),
                (
                    "ruta_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="rutas.rutaversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeccionActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=20)),
                ("fecha_habilitacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_limite", models.DateTimeField(blank=True, null=True)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                (
                    "ruta_actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones_actividad",
                        to="rutas.rutaactividad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=220)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(max_length=20)),
                (
                    "archivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidencias",
                        to="archivos.archivo",
                    ),
                ),
                (
                    "subido_por_docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidencias_subidas",
                        to="academico.docente",
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="rutas.expedienteseccion",
                    ),
                ),
                (
                    "seccion_actividad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidencias",
                        to="rutas.seccionactividad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeccionRuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(max_length=20)),
                (
                    "asignado_por_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rutas_seccion_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ruta_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones_asignadas",
                        to="rutas.rutaversion",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rutas_asignadas",
                        to="academico.seccion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="seccionactividad",
            name="seccion_ruta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="rutas.seccionruta",
            ),
        ),
        migrations.AddConstraint(
            model_name="rutaversion",
            constraint=models.UniqueConstraint(
                fields=("plantilla", "numero_version"),
                name="unique_version_por_ruta_plantilla",
            ),
        ),
        migrations.AddConstraint(
            model_name="seccionruta",
            constraint=models.UniqueConstraint(
                fields=("seccion", "ruta_version"),
                name="unique_ruta_version_por_seccion",
            ),
        ),
        migrations.AddConstraint(
            model_name="seccionactividad",
            constraint=models.UniqueConstraint(
                fields=("seccion_ruta", "ruta_actividad"),
                name="unique_actividad_por_seccion_ruta",
            ),
        ),
    ]
