# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0002_initial"),
        ("rutas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rutaversion",
            name="creado_por_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versiones_ruta_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rutaversion",
            name="plantilla",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versiones",
                to="rutas.rutaplantilla",
            ),
        ),
        migrations.AddField(
            model_name="rutaactividad",
            name="ruta_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="rutas.rutaversion",
            ),
        ),
        migrations.AddField(
            model_name="seccionactividad",
            name="completada_por_docente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actividades_ruta_completadas",
                to="academico.docente",
            ),
        ),
        migrations.AddField(
            model_name="seccionactividad",
            name="ruta_actividad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secciones_actividad",
                to="rutas.rutaactividad",
            ),
        ),
        migrations.AddField(
            model_name="evidencia",
            name="seccion_actividad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidencias",
                to="rutas.seccionactividad",
            ),
        ),
        migrations.AddField(
            model_name="seccionruta",
            name="cerrada_por_docente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rutas_cerradas",
                to="academico.docente",
            ),
        ),
        migrations.AddField(
            model_name="seccionruta",
            name="ruta_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secciones_asignadas",
                to="rutas.rutaversion",
            ),
        ),
        migrations.AddField(
            model_name="seccionruta",
            name="seccion",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ruta_asignada",
                to="academico.seccion",
            ),
        ),
        migrations.AddField(
            model_name="seccionactividad",
            name="seccion_ruta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="rutas.seccionruta",
            ),
        ),
        migrations.AddConstraint(
            model_name="rutaversion",
            constraint=models.UniqueConstraint(
                fields=("plantilla", "numero_version"),
                name="unique_version_por_ruta_plantilla",
            ),
        ),
        migrations.AddConstraint(
            model_name="seccionactividad",
            constraint=models.UniqueConstraint(
                fields=("seccion_ruta", "ruta_actividad"),
                name="unique_actividad_por_seccion_ruta",
            ),
        ),
    ]
