"""Resumen de Implementación A+S por docente - Sede Santiago (forms del cliente)."""

from encuestas import constantes as c
from encuestas.semillas import otras, pregunta, seccion

DEFINICION = {
    "codigo": "RESUMEN_IMPLEMENTACION_DOCENTE",
    "titulo": "Resumen de Implementación A+S por docente - Sede Santiago",
    "proceso": "RESUMEN_IMPLEMENTACION",
    "contexto_tipo": "DOCENTE",
    "secciones": [
        seccion("Datos del docente", [
            pregunta("Nombre Completo Docente (dos nombres y dos apellidos)", c.TEXTO_CORTO, dato_respondente="nombre"),
            pregunta("RUT (en el siguiente formato 15548766-5)", c.RUT, dato_respondente="rut"),
            pregunta("Indique un número de contacto (celular o fijo o ambos)", c.TEXTO_CORTO),
            pregunta("Correo Institucional", c.CORREO, dato_respondente="correo"),
            pregunta("Tipo de contrato", c.LISTA, [
                'Regular',
                'Adjunto',
            ]),
        ]),
        seccion("Asignatura", [
            pregunta("Año que esta reportando", c.ALTERNATIVA_UNICA, [
                '2025',
                '2026',
                '2027',
            ]),
            pregunta("Período en que se realizó la asignatura", c.LISTA, [
                'Diurno Otoño (primer semestre)',
                'Diurno Primavera (segundo semestre)',
                'Vespertino Tech (primer trimestre)',
                'Vespertino Tech (segundo trimestre)',
                'Vespertino Tech (tercer trimestre)',
                'Advance (primer trimestre)',
                'Advance (segundo trimestre)',
                'Advance (tercer trimestre)',
                'Otras',
            ]),
            pregunta("Campus", c.LISTA, [
                'Providencia',
                'El Llano',
                'Virtual',
                'Ambos campus',
                'Otras',
            ]),
            pregunta("Facultad", c.LISTA, [
                'Formación Integral',
                'Ciencias de la Salud',
                'Ciencias Sociales y Humanidades',
                'Derecho',
                'Educación',
                'Administración y Negocios',
                'Ingeniería',
                'Arquitectura, Construcción y Medio Ambiente',
            ]),
            pregunta("Carrera", c.LISTA, [
                'Ingeniería Comercial',
                'Ingeniería Comercial Vesp. Tech. Advance',
                'Ingeniería en Control de Gestión',
                'Curso FI con varias carreras en la misma sección',
                'Arquitectura',
                'Ingeniería en Construcción',
                'Medicina',
                'Enfermería',
                'Fonoaudiología',
                'Kinesiología',
                'Nutrición y Dietética',
                'Obstetricia y Puericultura',
                'Química y Farmacia',
                'Terapia Ocupacional',
                'Administración Pública',
                'Administración Pública Vesp. Tech. Advance',
                'Psicología',
                'Psicología Vesp. Tech.',
                'Periodismo',
                'Trabajo Social',
                'Pedagogía en Historia, Geografía y Ciencias Sociales',
                'Derecho',
                'Derecho Vesp. Tech.',
                'Licenciatura en Artes Visuales',
                'Pedagogía en Artes Visuales (Prosecusión)',
                'Pedagogía en Educación Básica',
                'Pedagogía en Educación Física',
                'Pedagogía en Educación Parvularia',
                'Pedagogía en Educación Parvularia (Prosecusión)',
                'Pedagogía en Inglés',
                'Pedagogía en Educación Diferencial',
                'Pedagogía en Lengua Castellana y Comunicación',
                'Ingeniería Civil Industrial',
                'Ingeniería Civil Informática',
                'Ingeniería Civil Química',
                'Publicidad y Comunicación Integral',
                'Odontología',
            ]),
            pregunta("Nombre de la asignatura  (Tal como aparece en el programa de estudios)", c.TEXTO_CORTO),
            pregunta("Nivel", c.LISTA, [
                '1',
                '2',
                '3',
                '4',
                '5',
                '6',
                '7',
                '8',
                '9',
                '10',
                '11',
                '12',
                '13',
                '14',
                '15',
            ]),
            pregunta("¿Cuantas secciones de una misma asignatura tiene a su cargo?", c.NUMERO, minimo=1, maximo=5),
            pregunta(
                "¿Qué secciones desea reportar?",
                c.SELECCION_MULTIPLE,
                [
                    'SEC. 1',
                    'SEC. 2',
                    'SEC. 3',
                    'SEC. 4',
                    'SEC. 5',
                    'Otras',
                ],
                obligatoria=False,
                ayuda="Si es que tiene a su cargo más de una sección con la misma asignatura",
                max_marcadas=5,
            ),
        ]),
        seccion("Proyectos A+S", [
            pregunta("¿En que consistió o consistieron los Proyectos A+S de este semestre o trimestre? Explíquelo en pocas líneas", c.TEXTO_LARGO),
            pregunta("Nota promedio A+S (Indicar el promedio de nota final de las secciones a su cargo, promedio simple)", c.NUMERO, minimo=1, maximo=7),
            pregunta("Cantidad total de estudiantes (Si tiene más de 1 sección a su cargo, súmelas)", c.NUMERO, minimo=0),
            pregunta("Cantidad de reprobados (Si tienen más de 1 sección, súmelas)", c.NUMERO, minimo=0),
            pregunta("Cantidad total de socios comunitarios (Si tiene más de 1 sección a su cargo, sume los SC)", c.NUMERO, minimo=0),
            pregunta("Tipo de socios comunitarios con los que trabajaron (Trate de asociarlo a alguna de estas categorías, si no es posible, agregue la clasificación en Otras)", c.SELECCION_MULTIPLE, [
                'Emprendedor(a) - Pyme',
                'Municipalidad',
                'Club de Adulto Mayor',
                'Junta de Vecinos',
                'Corporación',
                'Club deportivo',
                'Cesfam',
                'Fundación',
                'Colegio',
                'CDN Sercotec',
                'Universidad Autónoma',
                otras(),
            ]),
            pregunta("Cantidad total de beneficiarios o destinatarios. (Si tiene más de 1 sección a su cargo, sume los beneficiarios apróximados directos o indirectos)", c.NUMERO, minimo=0),
            pregunta("Tipo de beneficiarios o destinatarios", c.SELECCION_MULTIPLE, [
                'Personas Mayores',
                'Emprendedores',
                'Familias',
                'Personas con discapacidad',
                'Niños',
                'Estudiantes',
                'Funcionarios',
                'Padres o apoderados',
                'Mujeres Jefas de Hogar',
                otras(),
            ]),
            pregunta("Indique los diferentes ODS (objetivos de desarrollo sostenible) que fueron abordados por los proyectos dentro de la asignatura. Puede marcar todos los ODS que coincidan con las necesidades abordadas. Deben estar declarados en el formato de proyecto.", c.SELECCION_MULTIPLE, [
                'ODS 1: Fin de la pobreza',
                'ODS 2: Hambre cero',
                'ODS 3: Salud y bienestar',
                'ODS 4: Educación de calidad',
                'ODS 5: Igualdad de género',
                'ODS 6: Agua limpia y saneamiento',
                'ODS 7: Energía asequible y no contaminante',
                'ODS 8: Trabajo decente y crecimiento económico',
                'ODS 9: Industria, innovación e infraestructura',
                'ODS 10: Reducción de las desigualdades',
                'ODS 11: Ciudades y comunidades sostenibles',
                'ODS 12: Producción y consumo responsables',
                'ODS 13: Acción por el clima',
                'ODS 14: Vida submarina',
                'ODS 15: Vida de ecosistemas terrestres',
                'ODS 16: Paz, justicia e instituciones sólidas',
                'ODS 17: Alianzas para lograr los objetivos',
            ]),
            pregunta("¿Aplicó las 3 encuestas de satisfacción? Las encuestas son 3: una para los estudiantes, otra para el docente y otra para el socio comunitario.", c.ALTERNATIVA_UNICA, [
                'Sí.',
                'En proceso.',
                otras(),
            ]),
            pregunta("Envió la documentación solicitada como Evidencias (Carpeta de Evidencias: Formato de Proyecto, Acuerdos, Notas, Informes, Fotos y otras)", c.LISTA, [
                'Si',
                'No',
                'La estoy completando y la enviaré a la brevedad',
            ]),
            pregunta("Comentarios y/o sugerencias.", c.TEXTO_LARGO, obligatoria=False),
        ]),
    ],
}
