# Generated by Django 5.2.4 on 2026-09-25 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("nombre_almacenado", models.CharField(max_length=255)),
                ("ruta", models.CharField(max_length=500)),
                ("tipo_mime", models.CharField(max_length=120)),
                ("tamano_bytes", models.BigIntegerField()),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "subido_por_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archivos_subidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
