# Generated by Django 5.2.4 on 2026-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("storage_key", models.CharField(max_length=500, unique=True)),
                ("mime_type", models.CharField(max_length=120)),
                ("tamano_bytes", models.BigIntegerField()),
                ("hash_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecursoRepositorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=220)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("categoria", models.CharField(max_length=100)),
                (
                    "url_externa",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "visibilidad",
                    models.CharField(
                        choices=[("PUBLICO", "Público"), ("PRIVADO", "Privado")],
                        max_length=20,
                    ),
                ),
                ("estado", models.CharField(max_length=20)),
                ("fecha_publicacion", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
