# Generated by Django 5.2.4 on 2026-09-25 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("archivos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="archivo",
            name="cargado_por_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archivos_cargados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recursorepositorio",
            name="archivo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recursos_repositorio",
                to="archivos.archivo",
            ),
        ),
        migrations.AddField(
            model_name="recursorepositorio",
            name="publicado_por_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recursos_repositorio_publicados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
