# Generated by Django 5.2.4 on 2026-10-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='extension',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
