# Generated by Django 5.2.4 on 2026-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloqueFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=220)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("orden", models.IntegerField()),
                ("regla_visibilidad_json", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnlaceFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(editable=False, unique=True)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="FormularioPlantilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=60, unique=True)),
                ("titulo", models.CharField(max_length=220)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("proceso", models.CharField(max_length=60)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="FormularioVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_version", models.IntegerField()),
                ("estado", models.CharField(max_length=20)),
                (
                    "contexto_tipo",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("fecha_creacion", models.DateTimeField()),
                ("fecha_publicacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_inicio_vigencia", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin_vigencia", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OpcionPregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                ("valor", models.CharField(max_length=120)),
                ("orden", models.IntegerField()),
                ("es_otras", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PreguntaFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("tipo", models.CharField(max_length=40)),
                ("obligatoria", models.BooleanField()),
                ("orden", models.IntegerField()),
                ("configuracion_json", models.JSONField(blank=True, null=True)),
                ("regla_visibilidad_json", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_envio", models.DateTimeField()),
                ("origen", models.CharField(max_length=30)),
                ("es_historica", models.BooleanField()),
                (
                    "respondente_tipo",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "respondente_nombre",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                (
                    "respondente_correo",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "respondente_rut",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "nrc_snapshot",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "seccion_snapshot",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("estado_registro", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaOpcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaPregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_texto", models.TextField(blank=True, null=True)),
                (
                    "valor_numero",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("valor_fecha", models.DateTimeField(blank=True, null=True)),
                ("valor_booleano", models.BooleanField(blank=True, null=True)),
                (
                    "valor_correo",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("valor_rut", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "valor_escala",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("otro_texto", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
