# Generated by Django 5.2.4 on 2026-09-25 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormularioPlantilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("tipo", models.CharField(max_length=50)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FormularioVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_version", models.IntegerField()),
                ("estado", models.CharField(max_length=20)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versiones_formulario_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versiones",
                        to="encuestas.formularioplantilla",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloqueFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=220)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("orden", models.IntegerField()),
                (
                    "formulario_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloques",
                        to="encuestas.formularioversion",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="PreguntaFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=80)),
                ("texto", models.TextField()),
                ("tipo", models.CharField(max_length=30)),
                ("es_obligatoria", models.BooleanField()),
                ("orden", models.IntegerField()),
                ("ayuda", models.TextField(blank=True, null=True)),
                ("config_json", models.JSONField(blank=True, null=True)),
                (
                    "bloque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="encuestas.bloqueformulario",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="OpcionPregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.CharField(max_length=120)),
                ("etiqueta", models.CharField(max_length=220)),
                ("orden", models.IntegerField()),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="encuestas.preguntaformulario",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.AddConstraint(
            model_name="formularioversion",
            constraint=models.UniqueConstraint(
                fields=("plantilla", "numero_version"),
                name="unique_version_por_formulario_plantilla",
            ),
        ),
        migrations.AddConstraint(
            model_name="preguntaformulario",
            constraint=models.UniqueConstraint(
                fields=("bloque", "codigo"), name="unique_codigo_por_bloque"
            ),
        ),
        migrations.AddConstraint(
            model_name="opcionpregunta",
            constraint=models.UniqueConstraint(
                fields=("pregunta", "valor"), name="unique_valor_por_pregunta"
            ),
        ),
    ]
