# Generated by Django 5.2.4 on 2026-09-25 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archivos", "0001_initial"),
        ("encuestas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnlaceFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(editable=False, unique=True)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "formulario_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enlaces",
                        to="encuestas.formularioversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(max_length=20)),
                (
                    "enlace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas",
                        to="encuestas.enlaceformulario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaPregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_texto", models.TextField(blank=True, null=True)),
                (
                    "valor_numero",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("valor_fecha", models.DateField(blank=True, null=True)),
                ("valor_booleano", models.BooleanField(blank=True, null=True)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas",
                        to="encuestas.preguntaformulario",
                    ),
                ),
                (
                    "respuesta_formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_preguntas",
                        to="encuestas.respuestaformulario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaOpcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas",
                        to="encuestas.opcionpregunta",
                    ),
                ),
                (
                    "respuesta_pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones_seleccionadas",
                        to="encuestas.respuestapregunta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas_formulario",
                        to="archivos.archivo",
                    ),
                ),
                (
                    "respuesta_pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="encuestas.respuestapregunta",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="respuestapregunta",
            constraint=models.UniqueConstraint(
                fields=("respuesta_formulario", "pregunta"),
                name="unique_pregunta_por_respuesta_formulario",
            ),
        ),
        migrations.AddConstraint(
            model_name="respuestaopcion",
            constraint=models.UniqueConstraint(
                fields=("respuesta_pregunta", "opcion"),
                name="unique_opcion_por_respuesta_pregunta",
            ),
        ),
        migrations.AddConstraint(
            model_name="respuestaarchivo",
            constraint=models.UniqueConstraint(
                fields=("respuesta_pregunta", "archivo"),
                name="unique_archivo_por_respuesta_pregunta",
            ),
        ),
    ]
