# Generated by Django 5.2.4 on 2026-10-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioplantilla',
            name='tema_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
